qb_legs_params:
  chain_names: [lfoot_torso,lfoot_rfoot,lfoot_pelvis,rfoot_torso,rfoot_lfoot,rfoot_pelvis]
  chain_roots: [qb_legs_left_foot,qb_legs_left_foot,qb_legs_left_foot,qb_legs_right_foot,qb_legs_right_foot,qb_legs_right_foot]
  chain_ees: [qb_legs_torso_link,qb_legs_right_foot,qb_legs_pelvis_link,qb_legs_torso_link,qb_legs_left_foot,qb_legs_pelvis_link]

